-- MySQL Script generated by MySQL Workbench
-- Tue Feb  1 10:38:03 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema GameLib
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema GameLib
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `GameLib` DEFAULT CHARACTER SET utf8mb4 ;
USE `GameLib` ;

-- -----------------------------------------------------
-- Table `GameLib`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GameLib`.`roles` (
  `id_role` INT NOT NULL AUTO_INCREMENT,
  `rolename` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_role`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GameLib`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GameLib`.`users` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `firstname` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `pseudo` VARCHAR(255) NOT NULL,
  `password` CHAR(40) NOT NULL,
  `account_creation` DATE NOT NULL,
  `account_validation` DATE NOT NULL,
  `bio` TEXT NULL,
  `avatar` VARCHAR(255) NULL,
  `roles_id_role` INT NOT NULL,
  PRIMARY KEY (`id_user`),
  INDEX `fk_users_roles1_idx` (`roles_id_role` ASC),
  CONSTRAINT `fk_users_roles1`
    FOREIGN KEY (`roles_id_role`)
    REFERENCES `GameLib`.`roles` (`id_role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GameLib`.`games`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GameLib`.`games` (
  `id_game` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  `release_date` DATE NOT NULL,
  PRIMARY KEY (`id_game`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GameLib`.`platforms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GameLib`.`platforms` (
  `id_platform` INT NOT NULL AUTO_INCREMENT,
  `manufacturer` VARCHAR(255) NOT NULL,
  `model` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_platform`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GameLib`.`editors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GameLib`.`editors` (
  `id_editor` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `country` VARCHAR(45) NULL,
  PRIMARY KEY (`id_editor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GameLib`.`studios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GameLib`.`studios` (
  `id_studio` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `country` VARCHAR(45) NULL,
  PRIMARY KEY (`id_studio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GameLib`.`editors_has_studios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GameLib`.`editors_has_studios` (
  `id_editor` INT NOT NULL,
  `id_studio` INT NOT NULL,
  PRIMARY KEY (`id_editor`, `id_studio`),
  INDEX `fk_editors_has_studios_studios1_idx` (`id_studio` ASC),
  INDEX `fk_editors_has_studios_editors1_idx` (`id_editor` ASC),
  CONSTRAINT `fk_editors_has_studios_editors1`
    FOREIGN KEY (`id_editor`)
    REFERENCES `GameLib`.`editors` (`id_editor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_editors_has_studios_studios1`
    FOREIGN KEY (`id_studio`)
    REFERENCES `GameLib`.`studios` (`id_studio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GameLib`.`games_has_platforms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GameLib`.`games_has_platforms` (
  `id_game` INT NOT NULL,
  `id_platform` INT NOT NULL,
  PRIMARY KEY (`id_game`, `id_platform`),
  INDEX `fk_games_has_platforms_platforms1_idx` (`id_platform` ASC),
  INDEX `fk_games_has_platforms_games1_idx` (`id_game` ASC),
  CONSTRAINT `fk_games_has_platforms_games1`
    FOREIGN KEY (`id_game`)
    REFERENCES `GameLib`.`games` (`id_game`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_games_has_platforms_platforms1`
    FOREIGN KEY (`id_platform`)
    REFERENCES `GameLib`.`platforms` (`id_platform`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GameLib`.`studios_has_games`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GameLib`.`studios_has_games` (
  `id_studio` INT NOT NULL,
  `id_game` INT NOT NULL,
  PRIMARY KEY (`id_studio`, `id_game`),
  INDEX `fk_studios_has_games_games1_idx` (`id_game` ASC),
  INDEX `fk_studios_has_games_studios1_idx` (`id_studio` ASC),
  CONSTRAINT `fk_studios_has_games_studios1`
    FOREIGN KEY (`id_studio`)
    REFERENCES `GameLib`.`studios` (`id_studio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_studios_has_games_games1`
    FOREIGN KEY (`id_game`)
    REFERENCES `GameLib`.`games` (`id_game`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GameLib`.`users_has_games_has_platforms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GameLib`.`users_has_games_has_platforms` (
  `id_user` INT NOT NULL,
  `id_game` INT NOT NULL,
  `id_platform` INT NOT NULL,
  `rate` INT(2) NULL,
  PRIMARY KEY (`id_user`, `id_game`, `id_platform`),
  INDEX `fk_users_has_games_has_platforms_games_has_platforms1_idx` (`id_game` ASC, `id_platform` ASC),
  INDEX `fk_users_has_games_has_platforms_users1_idx` (`id_user` ASC),
  CONSTRAINT `fk_users_has_games_has_platforms_users1`
    FOREIGN KEY (`id_user`)
    REFERENCES `GameLib`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_games_has_platforms_games_has_platforms1`
    FOREIGN KEY (`id_game` , `id_platform`)
    REFERENCES `GameLib`.`games_has_platforms` (`id_game` , `id_platform`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
